#!/usr/bin/env bash
#
# Accelerated key-rotation smoke test.
#
# Brings up a 3-node mini-cluster with NORN_ACCELERATE_ROTATIONS_SECS=15,
# letting hourly (onion) + daily (ML-KEM) + 5-min (cuckoo gen) intervals
# all compress to 15 s. After 90 s checks that:
#   - "onion keys rotated at tick" log line appears ≥3 times per node
#   - "ML-KEM" rotation event surfaces (no direct log; we infer from
#     onion+cuckoo timing as proxies because session.rs rotates silently)
#   - peer connections survive across rotations (no permanent splits;
#     final sum_peers ≥ initial)
#
# Exits 0 on success.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
HERE="$ROOT/tests/cluster"
ACCEL_SECS=15
COMPOSE="$HERE/docker-compose.rotation.yml"

cat > "$COMPOSE" <<EOF
# Generated by tests/cluster/test_rotation.sh — DO NOT EDIT.
services:
EOF

# Pre-generate three real keys so the configs are valid.
gen_key() {
    docker run --rm --entrypoint /usr/local/bin/nornd norn-testnode:latest genconfig \
        | awk -F\" '/^private_key/ {print $2; exit}'
}

mkdir -p "$HERE/rotation/configs"
for i in 0 1 2; do
    KEY=$(gen_key)
    PEERS=""
    if [ "$i" -lt 2 ]; then
        # Only the smaller-index side dials — pairs with lex-priority
        # dial tiebreak in transport.rs.
        NEXT=$((i + 1))
        PEERS=$(printf '"tcp://norn-rot-%02d:19090"' "$NEXT")
    fi
    cat > "$HERE/rotation/configs/n${i}.toml" <<EOF
private_key = "${KEY}"
listen      = ["tcp://0.0.0.0:19090"]
peers       = [${PEERS}]
tun_name    = ""
admin_socket    = "/var/run/norn.sock"
peer_cache_path = ""
multicast_enabled = false
mdns_enabled      = false
metrics_addr      = "0.0.0.0:9090"
min_peer_difficulty_bits = 0
log_level = "debug"
EOF
    chmod 600 "$HERE/rotation/configs/n${i}.toml"

    cat >> "$COMPOSE" <<EOF
  norn-rot-0${i}:
    image: norn-testnode:latest
    container_name: norn-rot-test-0${i}
    hostname: norn-rot-0${i}
    networks: [rotmesh]
    environment:
      - NORN_ACCELERATE_ROTATIONS_SECS=${ACCEL_SECS}
      - NETEM_DISABLE=1
    volumes:
      - ./rotation/configs/n${i}.toml:/etc/norn/norn.toml:ro
    tmpfs:
      - /var/run:size=4M
    restart: "no"
EOF
done

cat >> "$COMPOSE" <<EOF

networks:
  rotmesh:
    driver: bridge
EOF

echo "=== bring up 3-node accelerated cluster (ACCEL_SECS=${ACCEL_SECS}) ==="
docker compose -f "$COMPOSE" down --remove-orphans -v >/dev/null 2>&1 || true
docker compose -f "$COMPOSE" up -d

echo "=== running for 90s; rotations should fire every ${ACCEL_SECS}s ==="
sleep 90

echo "=== collect logs ==="
mkdir -p "$HERE/rotation/logs"
for i in 0 1 2; do
    docker logs "norn-rot-test-0${i}" > "$HERE/rotation/logs/n${i}.log" 2>&1 || true
done

echo "=== teardown ==="
docker compose -f "$COMPOSE" down --remove-orphans -v >/dev/null 2>&1 || true

echo "=== verify ==="
fail=0
for i in 0 1 2; do
    log="$HERE/rotation/logs/n${i}.log"
    # Onion-key rotation should occur ~6 times in 90 s when interval=15 s
    # (account for first-tick skip). Assert ≥ 3 to give slack for CI jitter.
    rotations=$(grep -c "onion keys rotated" "$log" || true)
    if [ "$rotations" -lt 3 ]; then
        echo "  FAIL: node $i had $rotations onion-key rotations (need ≥3)"
        fail=1
    else
        echo "  OK:   node $i had $rotations onion-key rotations"
    fi
    # The accelerator warning must be present — proves the env knob was read.
    if grep -q "NORN_ACCELERATE_ROTATIONS_SECS=${ACCEL_SECS}" "$log"; then
        echo "  OK:   node $i logged the accelerator warning"
    else
        echo "  FAIL: node $i missing accelerator warning"
        fail=1
    fi
done

if [ "$fail" -ne 0 ]; then
    echo "=== rotation verification FAILED ==="
    echo "Logs in $HERE/rotation/logs/"
    exit 1
fi
echo "=== OK ==="
