#!/usr/bin/env python3
"""
Small-world topology generator for the test cluster.

Watts-Strogatz: each of N nodes has 2 ring-adjacent peers + 2 random
long-distance shortcut peers. Result: average path length ≈ log(N), with
plenty of FP-cuckoo and trust-ranking scenarios for the new architectural
hardening to exercise.

Outputs one TOML config per node into ./configs/n{i:02}.toml plus a
docker-compose.yml that wires them together on a single bridge network.

Run: python3 tests/cluster/topology.py
"""

from __future__ import annotations
import os
import random
import secrets
import subprocess
import sys
from pathlib import Path

N_NODES = 30
# Aim for a low-degree mesh that still routes interestingly.
# RING_DEGREE = 1 → 2 ring-adjacent peers per node (forward + back).
# SHORTCUT_DEGREE = 1 → 1 random long-distance peer per node (one direction;
# symmetry from other nodes' shortcuts adds ~1 more on average).
# Expected average degree ≈ 4, expected diameter ≈ log2(N) ≈ 4 hops.
RING_DEGREE = 1
SHORTCUT_DEGREE = 1
RNG_SEED = 0xC0FFEE      # deterministic for reproducible plots
BASE_TCP_PORT = 19001
METRICS_PORT = 9090

HERE = Path(__file__).resolve().parent
CONFIGS = HERE / "configs"
COMPOSE_PATH = HERE / "docker-compose.yml"


def gen_ed25519_priv_hex() -> str:
    """A 32-byte random seed; ed25519-dalek's SigningKey::from_bytes accepts this."""
    return secrets.token_hex(32)


def small_world_peers(n: int, ring: int, shortcuts: int, rng: random.Random) -> list[set[int]]:
    """Return adj[i] = set of node-indices i is wired to."""
    adj: list[set[int]] = [set() for _ in range(n)]
    # Ring
    for i in range(n):
        for k in range(1, ring + 1):
            j = (i + k) % n
            adj[i].add(j)
            adj[j].add(i)
    # Shortcuts (only added on the smaller-index side to avoid duplicates;
    # asymmetric wiring is fine because our transport's lex-dial guard makes
    # the smaller-pub side the canonical dialer anyway).
    for i in range(n):
        candidates = [j for j in range(n) if j != i and j not in adj[i]]
        rng.shuffle(candidates)
        for j in candidates[:shortcuts]:
            adj[i].add(j)
            adj[j].add(i)
    return adj


def write_configs(adj: list[set[int]], keys: list[str]) -> None:
    CONFIGS.mkdir(parents=True, exist_ok=True)
    for old in CONFIGS.glob("n*.toml"):
        old.unlink()
    for i in range(len(adj)):
        # A node dials only neighbours with HIGHER index — pairs with the
        # transport's lex-dial-priority tiebreak, gives deterministic
        # one-side-only dials, eliminates the simultaneous-dial race.
        dials = sorted(j for j in adj[i] if j > i)
        peers_lines = ", ".join(
            f'"tcp://norn-{j:02d}:{BASE_TCP_PORT}"' for j in dials
        )
        # In compose we expose nornd's TCP on a per-node host port
        # BASE_TCP_PORT+i so a host-side scraper can also poke if needed.
        cfg = f"""# Generated by tests/cluster/topology.py
private_key = "{keys[i]}"
listen      = ["tcp://0.0.0.0:{BASE_TCP_PORT}"]
peers       = [{peers_lines}]

# Test cluster runs overlay-only — no TUN, no kernel routing.
# All traffic flows through nornd's own session layer.
tun_name    = ""

admin_socket    = "/var/run/norn.sock"
peer_cache_path = ""

multicast_enabled = false
mdns_enabled      = false

# Bind the Prometheus /metrics endpoint on every interface so the
# scraper container can hit it.
metrics_addr      = "0.0.0.0:{METRICS_PORT}"

# Zero PoW: the test cluster is short-lived, every node is honest;
# Sybil resistance is exercised by dedicated unit tests.
min_peer_difficulty_bits = 0

log_level = "info"
"""
        (CONFIGS / f"n{i:02d}.toml").write_text(cfg)


def write_compose(n: int) -> None:
    """Emit docker-compose.yml: N nornd services + 1 scraper service."""
    services = []
    for i in range(n):
        services.append(
            f"""  norn-{i:02d}:
    image: norn-testnode:latest
    container_name: norn-test-{i:02d}
    hostname: norn-{i:02d}
    networks:
      - mesh
    volumes:
      - ./configs/n{i:02d}.toml:/etc/norn/norn.toml:ro
    # Per-node metrics also reachable from the host on this port for ad-hoc curl.
    ports:
      - "{METRICS_PORT + i}:{METRICS_PORT}"
    # NET_ADMIN lets the entrypoint install a NetEm qdisc on eth0 so the
    # routing layer experiences realistic wide-area delay/jitter/loss
    # instead of docker bridge's idealised 0ms / 0% link.
    cap_add:
      - NET_ADMIN
    restart: "no"
    tmpfs:
      - /var/run:size=4M"""
        )
    services.append(
        f"""  scraper:
    image: python:3.12-slim
    container_name: norn-test-scraper
    networks:
      - mesh
    volumes:
      - ./scraper.py:/scraper.py:ro
      - ./out:/out
    command: ["python3", "/scraper.py", "--nodes", "{n}",
              "--interval", "1", "--duration", "120",
              "--metrics-port", "{METRICS_PORT}", "--out-dir", "/out"]
    depends_on: [{', '.join(f'norn-{i:02d}' for i in range(n))}]"""
    )
    compose = (
        "# Generated by tests/cluster/topology.py — DO NOT EDIT.\n"
        "services:\n"
        + "\n\n".join(services)
        + "\n\nnetworks:\n  mesh:\n    driver: bridge\n"
    )
    COMPOSE_PATH.write_text(compose)


def main() -> int:
    rng = random.Random(RNG_SEED)
    adj = small_world_peers(N_NODES, RING_DEGREE, SHORTCUT_DEGREE, rng)
    keys = [gen_ed25519_priv_hex() for _ in range(N_NODES)]
    write_configs(adj, keys)
    write_compose(N_NODES)
    (HERE / "out").mkdir(exist_ok=True)
    # Lock down config perms (nornd refuses world-readable configs).
    for f in CONFIGS.glob("*.toml"):
        os.chmod(f, 0o600)
    print(f"OK: wrote {N_NODES} configs to {CONFIGS}/")
    print(f"OK: wrote {COMPOSE_PATH}")
    print(f"    average degree = {sum(len(a) for a in adj) / N_NODES:.1f}")
    print(f"    diameter:")
    # Quick BFS for diameter, just to give the operator a sanity number.
    from collections import deque
    longest = 0
    for src in range(N_NODES):
        dist = [-1] * N_NODES
        dist[src] = 0
        q = deque([src])
        while q:
            u = q.popleft()
            for v in adj[u]:
                if dist[v] < 0:
                    dist[v] = dist[u] + 1
                    q.append(v)
        longest = max(longest, max(dist))
    print(f"      {longest} hops (max shortest-path across all pairs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
